### PR TITLE
perf: remove mkdirp dependency

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
Thanks!

**Review by dsherret — CHANGES_REQUESTED** [review]
Seems to have introduced a regression. See CI output. We'll just have to update this code to not throw for existing directories.

**Comment by benmccann** [comment]
sorry, I can't figure out how to run the project locally. I've never used Deno before and am not familiar with what's happening in the build process. I noticed an error in the code and updated it, so hopefully that will get the tests passing. If not, I may need a little help with this one

**Comment by dsherret** [comment]
I think it should just be to run `npm install` in the root, then `cd packages/common`, then `npm run test`

**Comment by benmccann** [comment]
ah, cool. thanks. that worked! I was trying to build it from the root first, which wasn't working at all

**Comment by benmccann** [comment]
@dsherret would you be able to give this PR another peek now that the CI is passing? thanks!

**Review by dsherret — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
