### PR TITLE
perf: switch to tinyglobby to drop 15 dependencies

### PR DESCRIPTION
**Pull request by benmccann**
https://npmgraph.js.org/?q=fast-glob - 17 dependencies
https://npmgraph.js.org/?q=tinyglobby - 2 dependencies

I think the even better solution though would be to move globbing into user land. The users who want globbing can invoke it on their own and pass the result into `addSourceFilesAtPaths` so that users who don't need globbing don't have to pay that cost.

### CODE REVIEW

**Comment by benmccann** [comment]
@dsherret any chance you might be able to take a look at this? thanks!

**Comment by benmccann** [comment]
@dsherret thanks for the merge of https://github.com/dsherret/ts-morph/pull/1549. I've rebased this PR and updated it so that it's passing the CI now

**Review by dsherret — APPROVED** [review]
Thanks!

> I think the even better solution though would be to move globbing into user land.

Ship has sailed.

**Comment by dsherret** [comment]
Going to revert this one in https://github.com/dsherret/ts-morph/pull/1595 -- Maybe in a few years once things have played out with tinyglobby I'll switch back to that.

**Pull request merged**
